@startuml
title UML Class Diagram - High Level System Overview

package MTmotor-jig-mcu-firmware {
  class ArduinoSketch {
    +setup()
    +loop()
  }

  class Configuration {
    +{static} Configuration& GetInstance()
    +void BeginHardware()
    +void ToggleLogs()
    +void ReportFirmwareVersion()
  }

  class ControlSystem {
    +void Begin()
    +void CheckAndProcess()
    -void LogGeneralStatus() const
  }

  class DisplayManager {
    +void Begin()
    +void Draw(\nConfiguration::ControlMode control_mode, \nConfiguration::ControlAction control_action, \nconst String& status)
    -void DrawScreenItems(\nconst String screen_items[], \nconst uint8_t size_of_screen_items)
  }

  class InputManager {
    +void Begin()
    +Configuration::ControlAction Check(\nConfiguration::ControlMode control_mode)
  }

  class MotorManager {
    +void Begin()
    +void Actuate(\nConfiguration::ControlMode control_mode, \nConfiguration::ControlAction control_action, \nString& status_output)
    +void Actuate(\nConfiguration::ControlMode control_mode, \nConfiguration::ControlAction control_action, \nString& status_output)
    +void LogGeneralStatus(Configuration::ControlMode control_mode) const
    +bool homing() const
  }
}

package ArduinoLog {
  class Logging {
  }
}

package LiquidCrystal {
  class LiquidCrystal {
  }
}

package MT-rotary-encoder {
  class RotaryEncoder {
  }
}

package MT-arduino-momentary-button {
  class MomentaryButton {
  }
}

package MT-arduino-stepper-driver {
  class StepperDriver {
  }
}

ArduinoSketch "1" o-- "0..*" ControlSystem : Has
ArduinoSketch <.. Logging

Configuration <.. Logging

ControlSystem "1" o-- "1" Configuration : Has
ControlSystem "1" o- "1" DisplayManager : Has
ControlSystem "1" o- "1" InputManager : Has
ControlSystem "1" o- "1" MotorManager : Has
ControlSystem <.. Logging

DisplayManager "1" o-- "1" Configuration : Has 
DisplayManager "1" o-- "0..*" LiquidCrystal: Has

InputManager "1" o-- "1" Configuration : Has
InputManager "1" o-- "0..*" MomentaryButton : Has
InputManager "1" o-- "0..*" RotaryEncoder : Has
InputManager <.. Logging

MotorManager "1" o-- "1" Configuration : Has
MotorManager "1" o-- "0..*" StepperDriver : Has
MotorManager <.. Logging

@enduml